version: '3.9'
services:
  fit-friends.mongo:
    image: mongo:4.4
    restart: always
    container_name: fit-friends.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: fit-friends

    ports:
      - :27017:27017

    volumes:
      - fit-friends.mongo:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/fit-friends --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  fit-friends.mongo.ui:
    image: mongo-express
    restart: always
    container_name: fit-friends.mongo.ui
    ports:
      - :8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:test@fit-friends.mongo:27017/

  fit-friends.notify.fakesmtp:
    image: gessnerfl/fake-smtp-server:2.2.0
    restart: always
    container_name: "fit-friends.notify.fakesmtp"
    hostname: "fit-friends.notify.fakesmtp"
    ports:
      - "8025:8025"
      - "1083:8080"

  fit-friends.redis:
    image: redis:latest
    restart: always
    container_name: fit-friends.redis
    ports:
      - "6379:6379"
    environment:
      QUEUE_HOST: localhost
      QUEUE_PORT: 6379

volumes:
  fit-friends.mongo:
