# Создание тренировки
POST http://localhost:3000/api/trainings HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWYxOWU0Yjg1NGY3OTJmNzdmMGZlNGMiLCJlbWFpbCI6Im5ldzdAdXNlci5jb20iLCJuYW1lIjoiQWxleCIsImlhdCI6MTcxMTUyNDgyOSwiZXhwIjoxNzExNTI1NzI5fQ.MWMF0AwAjE596U4WiThZi6BfTtRjz0NigJWo1tHsbHY

{
  "name": "Yoga training",
  "backgroundImage": "background.jpg",
  "level": "Newby",
  "trainType": "Yoga",
  "duration": "10-30min",
  "price": 7000,
  "calories": 5000,
  "description": "Lorem ipsum sit dolorem amet",
  "gender": "Female",
  "videoURL": "video.mp4",
  "isSpecial": true

}
###

# Редактирование тренировки

PATCH http://localhost:3000/api/trainings/65f7ffb015ef515772b1365f HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWYxOWU0Yjg1NGY3OTJmNzdmMGZlNGMiLCJlbWFpbCI6Im5ldzdAdXNlci5jb20iLCJuYW1lIjoiQWxleCIsImlhdCI6MTcxMTUyODAyNiwiZXhwIjoxNzExNTI4OTI2fQ.A5eVKZXzZnN445FxDmHHtSN6yaUbR8qLAE4ZSghjmKk

{
    "name": "Yoga YOGA2",
    "price": 3500
}

###

# Детальная информация о тренировке
GET  http://localhost:3000/api/trainings/65f7ffb015ef515772b1365f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWYxOThlOWEyZDY3YWZkMGU2ZGI3YmQiLCJlbWFpbCI6Im5ldzFAdXNlci5jb20iLCJuYW1lIjoiQWxleCIsImlhdCI6MTcxMTA5NjA3MSwiZXhwIjoxNzExMDk2OTcxfQ.M-jgMZFqCFKBCBavqK55brdKclkgcF_G-scfA9kKJnU

###

# Список тренировок
GET  http://localhost:3000/api/trainings?isSpecial=false HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWYxOThlOWEyZDY3YWZkMGU2ZGI3YmQiLCJlbWFpbCI6Im5ldzFAdXNlci5jb20iLCJuYW1lIjoiQWxleCIsImlhdCI6MTcxMjY2NTE5MCwiZXhwIjoxNzEyNjY2MDkwfQ.nR1FEIw4-W5hNBkJcA6i_4y6sEGAFeNs0IPsAFMHa9o
###

# Мои заказы
GET http://localhost:3000/api/trainings/myOrders HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWYxOWU0Yjg1NGY3OTJmNzdmMGZlNGMiLCJlbWFpbCI6Im5ldzdAdXNlci5jb20iLCJuYW1lIjoiQWxleCIsImlhdCI6MTcxMjEyODA5MSwiZXhwIjoxNzEyMTI4OTkxfQ.UZOLsD16YKzAPzhcOtrO1OA84B8279GnSL7EaCWO660

###

# Заполнить базу данных начальными значениями

GET http://localhost:3000/api/trainings/seed/30 HTTP/1.1

###
