# Создание тренировки
POST http://localhost:3000/api/trainings HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWYxOWU0Yjg1NGY3OTJmNzdmMGZlNGMiLCJlbWFpbCI6Im5ldzdAdXNlci5jb20iLCJuYW1lIjoiQWxleCIsImlhdCI6MTcxMDc2NTE3NywiZXhwIjoxNzEwNzY2MDc3fQ.AjDYBJL6eOfXZ6fmfN9I8a4h8A5DtD6zCMjZlCDPKsY

{
  "name": "Yoga training",
  "backgroundImage": "background.jpg",
  "level": "Newby",
  "trainType": "Yoga",
  "duration": "10-30 мин",
  "price": 7000,
  "calories": 5000,
  "description": "Lorem ipsum sit dolorem amet",
  "gender": "Female",
  "videoURL": "video.mp4",
  "isSpecial": true

}
###

# Редактирование тренировки

###

# Детальная информация о тренировке

###

# Список тренировок

###

# Мои заказы

GET http://localhost:3000/api/trainings/myOrders?sortByField=trainingsOrderedCount&sortByOrder=1 HTTP/1.1
Content-Type: application/json


###
