# Загрузить изображение
POST http://localhost:3000/api/upload/image HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="800.jpeg"
Content-Type: image/jpeg


< ./800.jpeg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# Загрузить видео пользователя
POST http://localhost:3000/api/upload/file HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="video1.mov"
Content-Type: video/quicktime


< ./video1.mov
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# Загрузить сертификат тренера
POST http://localhost:3000/api/upload/file HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="file.pdf"
Content-Type: application/pdf


< ./file.pdf
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# Получить данные файла по ID
GET http://localhost:3000/api/upload/6602c2d9abf1682d62b13403 HTTP/1.1

###

GET http://localhost:3000/api/uploads/file.pdf
