# Регистрация пользователя
POST http://localhost:3000/api/users/signin HTTP/1.1
Content-Type: application/json

{
  "email": "new39@user.com",
  "name": "Alex",
  "password": "123456",
  "avatar": "avarar.jpg",
  "gender": "Male",
  "role": "User",
  "description": "lorem ipsum dolor sit amet",
  "location": "Pionerskaya",
  "backgroundImage": "background.png",
  "level": "Newby",
  "trainType": ["Running", "Yoga", "Boxing"],
  "isReadyTrain": true,
  "duration": "10-30 мин",
  "caloriesTarget": 3000,
  "caloriesDaily": 1000,
  "certificates": "certificate.pdf",
  "achievements": "lorem ipsum dolor sit amet"

}

###

# Вход в систему
POST http://localhost:3000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "new1@user.com",
  "password": "123456"
}

###

# Cценарий отзыва Refresh Token
POST http://localhost:3000/api/users/refresh HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWYxOWRiNWM3N2JiZTA2MTYwNDY0NzAiLCJlbWFpbCI6Im5ldzRAdXNlci5jb20iLCJuYW1lIjoiQWxleCIsInRva2VuSWQiOiI0OWY2OTI2Ny01MWQ2LTRjM2YtODJjYy02MGViNzljZTE4NTQiLCJpYXQiOjE3MTEwMDQ4NTUsImV4cCI6MTcxMTYwOTY1NX0.4GHXdkpyqqcMkg1ElurNWZQ-8vuGwED2m_ZzZG_Kbd4


###

# Детальная информация о пользователе
GET http://localhost:3000/api/users/65f198e9a2d67afd0e6db7bd HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWYxOThlOWEyZDY3YWZkMGU2ZGI3YmQiLCJlbWFpbCI6Im5ldzFAdXNlci5jb20iLCJuYW1lIjoiQWxleCIsImlhdCI6MTcxMTAwNTExNywiZXhwIjoxNzExMDA2MDE3fQ.kiOeta_7CYD5HSMtIW6Knaq-Zmh90CE8VTUcLpgGieE

###

# Редактирование информации о пользователе
PATCH http://localhost:3000/api/users/update HTTP/1.1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWYxOThlOWEyZDY3YWZkMGU2ZGI3YmQiLCJlbWFpbCI6Im5ld2VtYWlsQHVzZXIuY29tIiwibmFtZSI6IlNhbSIsImlhdCI6MTcxMTAwNjIyMiwiZXhwIjoxNzExMDA3MTIyfQ.Xz72Z1_WcxNcvU-llow7K_hat9GPsu1IBmoZVFqD8Po
Content-Type: application/json

{
  "name": "Alex"
}

###

# Список (каталог) пользователей
GET http://localhost:3000/api/users?location=Pionerskaya&trainType=Yoga,Running&level=Newby&page=1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWYxOThlOWEyZDY3YWZkMGU2ZGI3YmQiLCJlbWFpbCI6Im5ldzFAdXNlci5jb20iLCJuYW1lIjoiQWxleCIsImlhdCI6MTcxMTAxNDU1NSwiZXhwIjoxNzExMDE1NDU1fQ.It3-zZ1OiymNQyBMy2p6J-iKV1p_2U5r-rZrpaiiDSg

###



# Authorize user by accessToken

POST http://localhost:3000/api/users/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWYxYTJlMWRhODZjOGE2NDc2MjhkMmUiLCJlbWFpbCI6Im5ldzlAdXNlci5jb20iLCJuYW1lIjoiQWxleCIsImlhdCI6MTcxMDMzNjY0NCwiZXhwIjoxNzEwMzM3NTQ0fQ.4KzjWoQIdKD-x6_DGdIr0u8ezLRIRf-jcyp-HsmNqaM

###

# Index users list
GET http://localhost:3000/api/users?location=Pionerskaya&level=Newby HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWYxOWU0Yjg1NGY3OTJmNzdmMGZlNGMiLCJlbWFpbCI6Im5ldzdAdXNlci5jb20iLCJuYW1lIjoiQWxleCIsImlhdCI6MTcxMDQxMjkxMSwiZXhwIjoxNzEwNDEzODExfQ.czqKOGPOrf4g35vAxPO8tlHz3tkvjaChRZFijt9vvyU

###

# Index user friends
GET http://localhost:3000/api/users/friends HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWYxOWRiNWM3N2JiZTA2MTYwNDY0NzAiLCJlbWFpbCI6Im5ldzRAdXNlci5jb20iLCJuYW1lIjoiQWxleCIsImlhdCI6MTcxMDc5OTAwOCwiZXhwIjoxNzEwNzk5OTA4fQ.pmIDIAL2Wmi0eLCDjye7YJxdnKgfFP7aJskdpm3XLmY

###

# Edit user friendsList
GET http://localhost:3000/api/users/friends/65f198e9a2d67afd0e6db7bd HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWYxOWRiNWM3N2JiZTA2MTYwNDY0NzAiLCJlbWFpbCI6Im5ldzRAdXNlci5jb20iLCJuYW1lIjoiQWxleCIsImlhdCI6MTcxMDc5OTAwOCwiZXhwIjoxNzEwNzk5OTA4fQ.pmIDIAL2Wmi0eLCDjye7YJxdnKgfFP7aJskdpm3XLmY

###
