# Получение общего баланса: количество доступных тренировок.
GET http://localhost:3000/api/accounts/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWYxOThlOWEyZDY3YWZkMGU2ZGI3YmQiLCJlbWFpbCI6Im5ldzFAdXNlci5jb20iLCJuYW1lIjoiQWxleCIsImlhdCI6MTcxMTM1NjA1MywiZXhwIjoxNzExMzU2OTUzfQ.M21OXBoschqLvEzO7CbINLVSxGczEe8jf3bvGv7rafI

###

# Создание баланса.
POST http://localhost:3000/api/accounts/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWYxOThlOWEyZDY3YWZkMGU2ZGI3YmQiLCJlbWFpbCI6Im5ldzFAdXNlci5jb20iLCJuYW1lIjoiQWxleCIsImlhdCI6MTcxMTM1NjA1MywiZXhwIjoxNzExMzU2OTUzfQ.M21OXBoschqLvEzO7CbINLVSxGczEe8jf3bvGv7rafI
 {
  "userId": "65f198e9a2d67afd0e6db7bd",
  "trainingId": "65f7ffb015ef515772b1365f",
  "trainingsActive": "1"
 }

###

# Пополнение баланса.
PATCH  http://localhost:3000/api/accounts/add/65f800bfabf2d4bb55beb36b HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWYxOThlOWEyZDY3YWZkMGU2ZGI3YmQiLCJlbWFpbCI6Im5ldzFAdXNlci5jb20iLCJuYW1lIjoiQWxleCIsImlhdCI6MTcxMTM1NjA1MywiZXhwIjoxNzExMzU2OTUzfQ.M21OXBoschqLvEzO7CbINLVSxGczEe8jf3bvGv7rafI

{
  "trainingsCount": "10"
}

###

# Списание тренировок.
PATCH http://localhost:3000/api/accounts/use/65f800bfabf2d4bb55beb36b HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NWYxOThlOWEyZDY3YWZkMGU2ZGI3YmQiLCJlbWFpbCI6Im5ldzFAdXNlci5jb20iLCJuYW1lIjoiQWxleCIsImlhdCI6MTcxMTM1NjA1MywiZXhwIjoxNzExMzU2OTUzfQ.M21OXBoschqLvEzO7CbINLVSxGczEe8jf3bvGv7rafI


{
  "trainingsCount": "1"
}

###
